### ISSUE TITLE
Rename to QRona.info

### ISSUE THREAD

**Issue by CreativeCode** [privacybydesign/qrona#20]
Initial informal feedback by friends and colleagues about the name was divided. The name "IRMA-welkom" sounds friendly but it does not indicate that this tool is related to battling the Corona crisis. We do not expect everyone to find IRMA-welkom and, e.g., open the link to "IRMA-welkom" if it appears in their search results for contact-registration tools. The name also does not work well outside of the Netherlands. Based on this, we plan to consider renaming the project before announcing an official release.

**Comment by bvgastel** [comment]
Let's timebox this issue, and fix the name by Wed 4 Nov. Please list candidates below, so we can make a decision during a meeting.

**Comment by bvgastel** [comment]
Brainstorm during meeting: 
- CoroNoGo (.app);
- CoroNo (.nl).

**Comment by leonbotros** [comment]
We decided to change the name to QRona (QRona.info as domain)

**Comment by leonbotros** [comment]
- [ ] set DNS setting.
- [ ] change URLs in the webapp/backend accordingly.
- [ ] change texts.
- [ ] include a new logo.

**Comment by leonbotros** [comment]
PR regarding this issue: #41
